### ISSUE TITLE
proposal: index.html substitution

### ISSUE THREAD

**Issue by Menci** [chenxch/vite-plugin-dynamic-base#1]
This plugin just handles JS files but the `index.html` still just loads the module files from the origin host. We need to patch `index.html` to let redirect the initial module load to the CDN host.

I created another plugin to do this [in my project](https://github.com/lyrio-dev/ui/blob/a1a5689d22dff8e76eeaf36b98d89cb3fbce062f/vite/html-dynamic-tags-base.ts), which transforms `<link>` and `<script>` tags to JS calls of a given function (which should be declared in `index.html` file, together with placeholders to inject the JS code to).

See the usage of my current implementation: [plugin configuration](https://github.com/lyrio-dev/ui/blob/a1a5689d22dff8e76eeaf36b98d89cb3fbce062f/vite.config.ts#L99) and `index.html` (for [`<link>`](https://github.com/lyrio-dev/ui/blob/a1a5689d22dff8e76eeaf36b98d89cb3fbce062f/index.html#L124) and [`<script>`](https://github.com/lyrio-dev/ui/blob/a1a5689d22dff8e76eeaf36b98d89cb3fbce062f/index.html#L356)).

I could create a PR If you consider this feature useful.

**Comment by Menci** [comment]
Note: since the bug https://github.com/vitejs/vite/issues/5851, `index.html` substitution will only work with legacy builds after https://github.com/vitejs/vite/pull/6901 landed.

**Comment by Menci** [comment]
Integrating the loader sounds much more convenience but lose customization. For example if I load HTML and JS from different origins there's likely a chance that the HTML file is loaded but the JS is failed. If use a own loader the developer could attach a `onerror` event to the injected tag. But it's fine since there will be other methods to handle this.

I'll continue to follow up your implementation after https://github.com/vitejs/vite/pull/6901 landed.

**Comment by chenxch** [comment]
One scenario I can think of is the external dependencies in webpack, like the `vue` family bucket is loaded through the `a.cdn.com` path, and the project itself is loaded through the `b.cdn.com` path. At present, this plug-in is relatively simple to design for a whole project, of course, I also hope to improve this plug-in with your help.
