### ISSUE TITLE
src is /assets/xxx in html

### ISSUE THREAD

**Issue by feawesome** [chenxch/vite-plugin-dynamic-base#10]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/17822851/175856441-8f16149d-730f-4fa8-ac90-65ce3eda786c.png">

when i use 0.2.2, is   assets/xxx，when i upgrade the 0.4.6, the result is  /assets/xxx,  a  "/" was added,
excuse me，what is the reason for this

**Comment by chenxch** [comment]
In version 0.2.2, the default way of reading base is used as a marker bit. By default, base='/' will be replaced, which leads to the appearance of this difference.
