### ISSUE TITLE
ReferenceError: returnwindow is not defined

### ISSUE THREAD

**Issue by hotchicken1996** [chenxch/vite-plugin-dynamic-base#14]
版本4.4.0，
配置文件如下：
![image](https://user-images.githubusercontent.com/46117624/188530646-af95f20c-a226-46a7-a0f2-770fb0996eb7.png)
![image](https://user-images.githubusercontent.com/46117624/188530701-1239872b-86ea-47df-9814-853788b182f1.png)

项目打包后出现ReferenceError: returnwindow is not defined错误，错误位置如下截图：
![微信截图_20220906095340](https://user-images.githubusercontent.com/46117624/188530466-faaf52ef-d310-4ae4-a2a9-f8e545711619.png)

这个问题改如何解决？

**Comment by chenxch** [comment]
方便提供一个较小的demo么，如果是指从表面去分析插件只是做了一个repalce的操作，可能原来和return之间就没有空格？所以还需要一个demo详细排查。

**Comment by chenxch** [comment]
> 方便提供一个较小的demo么，如果只是从表面去分析插件只是做了一个repalce的操作，可能原来和return之间就没有空格？所以还需要一个demo详细排查。

**Comment by hotchicken1996** [comment]
@chenxch 我新建了一个demo过程中找到了问题出现的地方，在我使用路由懒加载时出现了上述问题。
![image](https://user-images.githubusercontent.com/46117624/188768739-f70f8f3a-c3de-4fae-bddb-340c87f5d3a0.png)

demo地址：https://github.com/hotchicken1996/vite-react-test-base.git
但我不清楚原因为何，以及如何解决，求解答

**Comment by chenxch** [comment]
收到，晚上我会对这个demo进行测试排查

**Comment by qyxx** [comment]
> 

vite 默认 base 都是字符串的，从 dist 可以看到正常的代码是这样的
```javascript
fj=function(f){return"/test/"+f}
```
使用插件后变为
```javascript
fj=function(f){returnwindow.__dynamic_base__+f}
```
还是按照你之前原先的思路去完善吧，用 ast 来修改代码

**Comment by chenxch** [comment]
其实可以做一个小操作也行,当时我还是会默认集成到插件中
```
publicPath: ' window.__dynamic_base__',
```

**Comment by chenxch** [comment]
@hotchicken1996 升级到0.4.5版本
