### ISSUE TITLE
innerHTML插入内容单双引号问题

### ISSUE THREAD

**Issue by jgsrty** [chenxch/vite-plugin-dynamic-base#17]
### 双引号
![image](https://user-images.githubusercontent.com/25652828/199660742-6b3a9620-8d3c-443a-9c0a-e7a979562524.png)
### 单引号
![image](https://user-images.githubusercontent.com/25652828/199660790-fccabed3-8a43-4814-bb3c-143deaf0c48f.png)
### 这里替换的是双引号
![image](https://user-images.githubusercontent.com/25652828/199660969-58885066-ba8d-4533-95c2-6c15b2a196d1.png)
### 在低版本浏览器中，innerHTML插入单引号的时候，替换的地址前缀为双引号，无法解析直接拼接成了字符串
![image](https://user-images.githubusercontent.com/25652828/199661956-87b30a2c-9c9a-4d2e-bb46-5623b6c46874.png)
### Google浏览器版本
版本 63.0.3214.0（开发者内部版本） （64 位）

**Comment by chenxch** [comment]
方便提供个demo么，正常这个变量在运行时是已经转换成对应值的。

**Comment by jgsrty** [comment]
我尝试用空的项目无法复现这个问题
在我的项目中generateBundle这个钩子，code里面innerHTML有的是双引号，有的是单引号
可否在插件中兼容下这个引号问题？😂
![image](https://user-images.githubusercontent.com/25652828/199674101-3dfe1430-7a13-452e-94dd-b35aad834699.png)

**Comment by chenxch** [comment]
能否提供一下你的chunk.code文本，问题的核心在于这份chunk中为何会是单引号，我们应该要先排查清楚这点。

**Comment by jgsrty** [comment]
是的 我也在排查这个问题出现原因

**Comment by jgsrty** [comment]
😊问题定位到了，样式中设置伪元素的content就会导致打包后的样式插入的时候是单引号（content内容默认是双引号的）
[这个demo可以复现](https://github.com/jgsrty/vite-plugin-dynamic-base)
大佬有空给兼容下吧✌

**Comment by jgsrty** [comment]
#### 导致此问题的原因
![image](https://user-images.githubusercontent.com/25652828/199921796-c1b842c7-df28-438a-bdbf-338f6c5878b9.png)
#### 打包后的结果
![image](https://user-images.githubusercontent.com/25652828/199921943-1398eb9d-7e54-494b-ac93-0069f771e448.png)
#### 在低版本浏览器中无法识别
![image](https://user-images.githubusercontent.com/25652828/199922174-16d9f381-193e-43fd-9492-fc3b9dd6facc.png)

**Comment by chenxch** [comment]
十分感谢你的定位，我会在尽快进行兼容处理，并且和你反馈。

**Comment by chenxch** [comment]
hello~~, 你可以尝试升级到0.4.6版本哈
原来计划使用swc对齐进行ast转换后替换，但是目前阶段还是不太了解这个东西，以至于这个方案并未落地，只能是先用目前的判断方式去处理了。

**Comment by chenxch** [comment]
@jgsrty 目前是否还有问题哈

**Comment by jgsrty** [comment]
> @jgsrty 目前是否还有问题哈

在我的项目中还是有些问题😰，还是有部分图片显示有问题，我在排查原因

**Comment by chenxch** [comment]
> 我用了最新的0.4.6，在我的项目中有一些图片正常显示了，但还是有部分图片无法显示😰，目前看还是引号拼接的问题，我在排查原因

如果有需要我这边支持的地方，随时回复我哈

**Comment by jgsrty** [comment]
#### hello，问题应该是出在这里
![image](https://user-images.githubusercontent.com/25652828/200483396-aab30b0f-78d8-4130-be34-214c5c3cf09d.png)
#### 当有多个图片地址时，0.4.6 打包后的结果，example中未改动即可复现此问题
![image](https://user-images.githubusercontent.com/25652828/200485495-301d2ca4-9a94-45fb-9165-efa48c857fd0.png)

#### 所以这里是否应该匹配第一个innerHTML的位置来判断图片地址内容是否为单双引号？

**Comment by chenxch** [comment]
```
a.innerHtml = 'background-imgae:url(/__dynamic_base__/asset/xx.png);.a:::after{content:""};'background-imgae:url(/__dynamic_base__/asset/dd.png)'
=>
["a.innerHtml = 'background-imgae:", 'asset/xx.png);.a:::after{content:""};background-imgae:', "asset/dd.png)'"]
```
我大概知道原因了，我应该保留之前写prefixQuote和suffixQuote
```
a.innerHtml = 'background-imgae: url('+window.xx+'/asset/xx.png);.a:::after{content:""};background-imgae:url("+window.xx+"/asset/dd.png)'
正确应该是：
a.innerHtml = 'background-imgae: url('+window.xx+"/asset/xx.png);.a:::after{content:""};background-imgae:url("+window.xx+'/asset/dd.png)'
```

**Comment by jgsrty** [comment]
嗯，麻烦尽快修复下吧~谢谢啦

**Comment by chenxch** [comment]
> 嗯，麻烦尽快修复下吧~谢谢啦

我先临时根据你说的方案先调整，感觉要加快swc的版本开发了。

**Comment by chenxch** [comment]
0.4.7版本
