### ISSUE TITLE
处理拼接时的问题

### ISSUE THREAD

**Issue by jgsrty** [chenxch/vite-plugin-dynamic-base#19]
### 字符拼接的写法不对，这样会导致最终拼接的结果为: 1x2x3x4  =>  1x22x33x4
![image](https://user-images.githubusercontent.com/25652828/212278289-afaa3bb1-6af7-4284-a57c-e98fb5aca023.png)

### 低版本浏览器会导致样式错乱
![image](https://user-images.githubusercontent.com/25652828/212279984-b87e8fee-9d75-4080-9d65-507c73683dff.png)

### example中的demo直接build可以复现此问题
![image](https://user-images.githubusercontent.com/25652828/212278730-57e0e681-86bb-4597-88cd-68b851b7b193.png)

**Comment by chenxch** [comment]
感谢反馈和修复， 代码已经进行review了哈

**Comment by chenxch** [comment]
0.4.8已发布
