### ISSUE TITLE
Issues with transforming css-in-js urls

### ISSUE THREAD

**Issue by joarfish** [chenxch/vite-plugin-dynamic-base#22]
Hello! Thanks for your work on this, its been quite helpful to us! :+1: 

I have encountered two issues with transforming CSS-in-JS urls:

1. They are only transformed if the output format is set to `system` (cf. `transformChunk` function in transform.ts). Could you explain the reasoning behind this? Is there a specific rationale for this choice?
2. If I remove that condition in transform.ts the transformation basically works, but the wrong quotation marks are used, breaking the js-code.

Example:

```
const o={backgroundImage:"url(__dynamic_base__/assets/foo.png)"};
``` 
Is transformed to
```
const o={backgroundImage:"url(' + window.__dynamic_base__ + '/assets/foo.png)"};
``` 

I looked into `replaceUrl` in utils.ts and noticed that there may be some flaws in the logic. First of all, it is assumed that the quotes used are always the same, which they may not. Secondly, determining whether single or double quotes are used is based on the assumption that you'll have an uneven number of quotation marks on the "left" side of the code split at the location that needs transformation. That is not a valid assumption to infer the required quotation marks, though. There are a number of reasons you may have an uneven number of quotation marks in the split part. For example the code may contain `foo.split("'")` or strings like `"The user's password has not changed."`. In our code we have strings with english text containing `'`, throwing off the algorithm.

So, I think this approach should be replaced with a more robust one.  I'm currently exploring potential solutions on my end too and would be glad to contribute an improved mechanism for transforming CSS-in-JS URL functions.

I look forward to your thoughts and feedback on this matter. Thank you for your time.

**Comment by chenxch** [comment]
Thank you for your recognition of my work. Let me answer your question first. It is found in the compatible official legacy plug-in that the code format of the legacy part is system, and the css is written into the js file, so I made this part processing.
Rather than talking about quotation marks or the way of replacement, I have always wanted to change a way to achieve it, such as converting swc to ast and then replacing it, and handing over the splicing work to these parsing libraries, but I have not implemented it. I am so sorry.

**Comment by chenxch** [comment]
You are really awesome, you accomplished this feat so quickly, I did a test and found that there is a little problem in modulepreload, sorry my network can't upload screenshots, you can test it through the examples in the project.
```js
// index.[hash].js
const Io="modulepreload",Mo=function(e){return window.__dynamic_base__/+e}
```

**Comment by chenxch** [comment]
```ts
export function replaceInStringLiteral(literal: StringLiteral, base: string, placeholder: string): string {
  const quoteMark = literal.raw.charAt(0);
  const regex = new RegExp(base, 'g');
  // Keep track of whether we need to add quotation marks at the beginning/end of the
  // final output
  let withEndQuote = true;
  let withStartQuote = true;

  const c = literal.value.replace(regex, (match, index, original) => {
    let prefix = `${quoteMark}+`;
    let suffix = `+${quoteMark}`;

    if (index === 0) {
      prefix = '';
      withStartQuote = false;
    }

    if (index + match.length === original.length) {
      suffix = '';
      withEndQuote = false;
    }

    return `${prefix}${placeholder}${suffix}/`;
  });

  const prefix = withStartQuote ? quoteMark : '';
  const suffix = withEndQuote ? quoteMark : '';
  const result = `${prefix}${c}${suffix}`

  return result.endsWith('/') ? `${result.slice(0, -1)}+${quoteMark}/${quoteMark}` : result;
}

```

**Comment by chenxch** [comment]
This should be enough, I am looking forward to your PR.

**Comment by joarfish** [comment]
The PR is open https://github.com/chenxch/vite-plugin-dynamic-base/pull/23

I simplyfied `transformChunk` even further to account for the issue you mentioned. I tested the example project and added some tests. Please have a look as well.
