### ISSUE TITLE
浏览器访问地址问题

### ISSUE THREAD

**Issue by chimu23** [chenxch/vite-plugin-dynamic-base#26]
![image](https://github.com/chenxch/vite-plugin-dynamic-base/assets/39324019/32bf6962-12f7-46e4-8980-26f76f424b88)
你好，我在 vite+vue3项目中设置 base 为 /__dynamic_base__/ 的时候，该项目下的所有路由访问都会加上这个前缀，我对配置这方面还不是太了解；我想要的效果就是上面的地址是不携带/__dynamic_base__/，但是加载的资源还是保持下图所示这样，请问我该如何设置呀。万分感激
![image](https://github.com/chenxch/vite-plugin-dynamic-base/assets/39324019/4242d1e5-748a-402d-a977-4498acddb9bb)

**Comment by chenxch** [comment]
方便提供一个最小复现demo么？

**Comment by chimu23** [comment]
> 方便提供一个最小复现demo么？

https://github.com/chimu23/tmp_test 这边还没有使用 vite-plugin-dynamic-base ，但是我就是想访问的时候不需要携带 /aaa 这样

**Comment by chenxch** [comment]
我大概知道你的问题了，你需要做一下区分模式
```
export default ({ mode }) => {
  return defineConfig({
    base: mode === 'production' ? '/dynamic_base/' : '/'
  })
}

```

**Comment by chimu23** [comment]
> 我大概知道你的问题了，你需要做一下区分模式
> 
> ```
> export default ({ mode }) => {
>   return defineConfig({
>     base: mode === 'production' ? '/dynamic_base/' : '/'
>   })
> }
> ```

但是在生产环境上，/dynamic_base/ 还是会一直显示在浏览器url上吧，我要的就是去掉这个，但是内置的请求资源还是保留

**Comment by chenxch** [comment]
不应该吧，这个只是作用于资源，你的url不应该是html么

**Comment by chenxch** [comment]
2个排查点，一个是dynamicBase里面的publicPath参数配置了么，一个是检查下你的路由base

**Comment by chimu23** [comment]
> 不应该吧，这个只是作用于资源，你的url不应该是html么

我也是这么认为的，但是只要是设定了 base，url上就一定会携带上这个，我很疑惑

**Comment by chimu23** [comment]
可能我表达的还不是很明确，我是指，从 https://github.com/chimu23/tmp_test （就是vue官方起的 demo，只是改了 base 的配置） 这个 demo 中，只要我配置了 base 的值，那么就会反应在 url 上，而我想要的效果是 url 上没有 base 配置的这个值，而 dynamic-base 插件是动态的修改了访问路径，但/dynamic_base/这个也还是会反应在 url 上，所以我可能比较想知道怎么从 url 上去掉 base 设定的值

**Comment by chimu23** [comment]
嗯，通过代理解决了
