### ISSUE TITLE
Does not add dynamic base path to fonts with .woff extension

### ISSUE THREAD

**Issue by darkangel081195** [chenxch/vite-plugin-dynamic-base#4]
**#Issue**
The plugin is not adding dynamic base path to font files with woff extenstion.

**#Steps to Reproduce**
1. Created a sample vue 3 project with font file present inside public/fonts
2. Build the project and run the preview
3. Checking network tab, font files are loaded without base path

**Comment by chenxch** [comment]
您反馈的问题稍后我会进行处理，如果您比较紧急的话，可以试着将woff文件放到src目录下。 修复完成后我会通知您。

**Comment by chenxch** [comment]
I have conducted related tests, woff can be loaded normally. If it is convenient, you can provide a demo.

**Comment by darkangel081195** [comment]
@chenxch I will work on creating a reproducible repo in parallel. But just as a note, issue is when we are trying to load a font file present in public folder. 

// index.scss
@font-face {
  font-family: "Ionicons";
  src: url('/fonts/ionicons.woff') format("woff");
  font-weight: normal;
  font-style: normal;
 }

the file mentioned in above url is present under public so after build it is available from dist .

Thanks.

**Comment by chenxch** [comment]
Are you sure that `index.scss` loads correctly into `ionicons.woff`? Shouldn't the path point to `public/fonts/ionicons.woff`? First of all, you have to make sure that the relative path is correct, not that it is compiled in the dist path.

**Comment by chenxch** [comment]
@darkangel081195 Has your issue been resolved?
