### ISSUE TITLE
Replacement for template strings does not work

### ISSUE THREAD

**Issue by leifmarcus** [chenxch/vite-plugin-dynamic-base#8]
When bundling the application for production with the terser minifier, the `__dynamic_base__` is not overridden, when it appears inside a template string like `/__dynamic_base__/${e}`. (After the compression, the preload helper will have a code like that for saving deps, that are already loaded).

This is related to the `replaceQuotes` function inside the plugin utils.
https://github.com/chenxch/vite-plugin-dynamic-base/blob/90b196954e7c8c7002a9cf8970aea3160c7af2d0/src/core/utils.ts#L8

A suggested change would be:

```js
function replaceQuotes(mark, placeholder, code) {
    const singleMark = `'${mark}`;
    const singlePlaceholder = `${placeholder}+'/`;
    const doubleMark = `"${mark}`;
    const doublePlaceholder = `${placeholder}+"/`;
    const templateMark = `\`${mark}`;
    const templatePlaceholder = `\`\$\{${placeholder}\}/`;
    return replace(doubleMark, doublePlaceholder, replace(singleMark, singlePlaceholder, replace(templateMark, templatePlaceholder, code)));
}
```

**Comment by chenxch** [comment]
@leifmarcus Thanks for your feedback, the fix version 0.4.3 has been released.

**Comment by modten** [comment]
Still encounter this problem with 1.0.0.
The ast function doesn't seem to handle TemplateLiteral.

**Comment by joarfish** [comment]
@modten Yes, you might be right. Can you open a new issue with some example code and your build target?

**Comment by modten** [comment]
@joarfish Sorry, I think there is no need to delve into this problem, because after I use the latest versions of vite and terser, this problem no longer exists.

The steps that caused the original problem were to use `vite@2.9.16` and `@vitejs/plugin-vue@2.3.4`, then use `defineAsyncComponent` to load the component asynchronously, and finally use `terser` for compression at build time. Then you can get the code where the problem occurred:

```js
e=`/__dynamic_base__/${e}`
```

```js title="App.vue"
const HelloWorld = defineAsyncComponent(() => import(`./components/HelloWorld.vue`))
```

```js title="vite.config.js"
{
   build: {
     minify: "terser"
   }
}
```

**Comment by joarfish** [comment]
@modten Thanks for the info. Glad that it works for you with the upgraded versions 👍 

@chenxch I can still have a look at template literals next week because I think they are not taken into account.
