### ISSUE TITLE
polyfill-modern.js is not transformed

### ISSUE THREAD

**Issue by feawesome** [chenxch/vite-plugin-dynamic-base#9]
version 0.4.2

**Comment by chenxch** [comment]
@feawesome Can you please give me details or examples?

**Comment by feawesome** [comment]
> @feawesome Can you please give me details or examples?

my vite config is 
<img width="648" alt="image" src="https://user-images.githubusercontent.com/17822851/174930047-30372646-c2ba-460e-8231-cb9620157fb7.png">

after building, my html  has a tag 
<img width="789" alt="image" src="https://user-images.githubusercontent.com/17822851/174930196-b2fc42dc-8d68-4e11-ae6b-413e692c7a23.png">

other tags is fine

**Comment by feawesome** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/17822851/174930675-e32848c1-6a50-4522-a320-6acefea39c8a.png">

**Comment by chenxch** [comment]
@feawesome Got it, tonight I'll align it to fix it, and I'll let you know when it's done.

**Comment by chenxch** [comment]
@feawesome Is your `base` already configured?

**Comment by chenxch** [comment]
> > 
> 
> thank you , dear
> 
> yeah, i configured base

OK, have a good day.

**Comment by feawesome** [comment]
Is it reoccurring in your environment？

**Comment by chenxch** [comment]
> Is it reoccurring in your environment？

Yes, since `modernPolyfills` mode needs to be handled separately, a compatible version should be released tonight.

**Comment by feawesome** [comment]
ok，thank you dear

**Comment by chenxch** [comment]
@feawesome try 0.4.4

**Comment by feawesome** [comment]
nice! dear, no problem with it， thank you !

**Comment by feawesome** [comment]
Are you chinese ?  whould you give me wechat

**Comment by feawesome** [comment]
would you give me  wechat ?

**Comment by chenxch** [comment]
If the problem is solved, you can contact me through email or discord.
